server:
  port: 8081

contact:
  message: Welcome to Shop Sphere QA-Lead contact
  contactDetails:
    name: Yasura Laksitha - QA Lead
    email: yasura.dev@gmail.com
    onCallSupport:
      - (555) 456-7890
      - (555) 654-3210

