server:
  port: 8081

contact:
  message: Welcome to Shop Sphere product-service production owner contact
  contactDetails:
    name: Yasura Laksitha - production owner
    email: yasura.dev@gmail.com
  onCallSupport:
    - (555) 456-7890
    - (555) 654-3210

